apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: dedalus-jmeter
message: >-
  The following service(s) have been created in your current project.
  
         Application Name: jmeter
      Application Version: 0.0.1

metadata:
  annotations:
    description: >- 
      Lorem ipsum
    iconClass: icon-d4center
    openshift.io/display-name: JMeter on OpenShift
    openshift.io/documentation-url: >-
      https://confluence.dedalus.eu/x/5jJPAg
    openshift.io/long-description: >-
      Lorem ipsum
    openshift.io/provider-display-name: Dedalus S.p.A.
    openshift.io/support-url: >-
      https://confluence.dedalus.eu/x/5jJPAg
    tags: 'dedalus-jmeter-openshift,dedalus'
  name: dedalus-jmeter-openshift
objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      annotations:
        template.alpha.openshift.io/wait-for-ready: 'true'
      labels:
        app: jmeter
      name: jmeter
    spec:
      replicas: 1
      revisionHistoryLimit: 5
      selector:
        app: jmeter
        deploymentconfig: jmeter
      strategy:
        activeDeadlineSeconds: 1800
        type: Rolling
#        resources:
#          limits:
#            cpu: '200m'
#            memory: '200Mi'
#          requests:
#            cpu: '100m'
#            memory: '100Mi'
      template:
        metadata:
          labels:
            app: jmeter
            deploymentconfig: jmeter
        spec:
          containers:
            - env:
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: metadata.namespace
                - name: REMOTE_HOST
                  value: '${P_REMOTE_HOST}'
                - name: REMOTE_PORT
                  value: '${P_REMOTE_PORT}'
                - name: CONTEXT
                  value: '${P_CONTEXT}'
                - name: GITHUB_REPO
                  value: '${P_GITHUB_REPO}'
              image: >-
                350801433917.dkr.ecr.eu-west-1.amazonaws.com/enterprise-architect/jmeter:0.0.2-SNAPSHOT
              imagePullPolicy: Always
              name: jmeter
#              resources:
#                limits:
#                  cpu: '200m'
#                  memory: '200Mi'
#                requests:
#                  cpu: '100m'
#                  memory: '100Mi'
          terminationGracePeriodSeconds: 30
      test: false
      triggers:
        - type: ConfigChange
parameters:
  - description: >-
      Service name
    displayName: Service name
    name: P_REMOTE_HOST
    value: ''
  - description: >-
      Port
    displayName: Port
    name: P_REMOTE_PORT
    value: ''
  - description: >-
      Context
    displayName: Context
    name: P_CONTEXT
    value: ''
  - description: >-
      GitHub Repo
    displayName: GitHub Repo
    name: P_GITHUB_REPO
    value: ''
